services:
  - type: web
    name: medstock-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn medstock_backend.wsgi:application --log-file -
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
    plan: free

    # Run migrations after deploy
    postDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
